<?php

use Illuminate\Database\Seeder;
use App\Role;
use App\User;
class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $data = [
            [
                "id"=>1,
                "role_id"=>1,
                "name"=>"admin",
                "image"=>"user/foto.png",
                "email"=>"admin@admin.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>2,
                "role_id"=>2,
                "name"=>"member",
                "image"=>"user/foto.png",
                "email"=>"member@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>3,
                "role_id"=>3,
                "name"=>"koordinator",
                "image"=>"user/foto.png",
                "email"=>"coordinator@gmail.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>4,
                "role_id"=>2,
                "name"=>"Agus Firyanto",
                "image"=>"user/foto.png",
                "email"=>"agus@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>5,
                "role_id"=>2,
                "name"=>"Martin/Aning",
                "image"=>"user/foto.png",
                "email"=>"martin@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>6,
                "role_id"=>2,
                "name"=>"Harun/Yumi",
                "image"=>"user/foto.png",
                "email"=>"harun@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>7,
                "role_id"=>2,
                "name"=>"Maptuhul Illahi",
                "image"=>"user/foto.png",
                "email"=>"maptuhul@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>8,
                "role_id"=>2,
                "name"=>"Budi/Erika",
                "image"=>"user/foto.png",
                "email"=>"budi@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>9,
                "role_id"=>2,
                "name"=>"Tidak dikenal",
                "image"=>"user/foto.png",
                "email"=>"unknown@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>10,
                "role_id"=>2,
                "name"=>"Nuridwan",
                "image"=>"user/foto.png",
                "email"=>"nuridwan@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>11,
                "role_id"=>2,
                "name"=>"Zakiudin",
                "image"=>"user/foto.png",
                "email"=>"zakiudin@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>12,
                "role_id"=>2,
                "name"=>"Muhammad Januar P",
                "image"=>"user/foto.png",
                "email"=>"januar@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>13,
                "role_id"=>2,
                "name"=>"Badruzzaman/Jenny",
                "image"=>"user/foto.png",
                "email"=>"badruzzaman@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>14,
                "role_id"=>2,
                "name"=>"Dadang",
                "image"=>"user/foto.png",
                "email"=>"dadang@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>15,
                "role_id"=>2,
                "name"=>"H. Dulatif",
                "image"=>"user/foto.png",
                "email"=>"hdulatif@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>16,
                "role_id"=>2,
                "name"=>"Riki/Heri",
                "image"=>"user/foto.png",
                "email"=>"riki@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>17,
                "role_id"=>2,
                "name"=>"Hari Sodikin/Anis",
                "image"=>"user/foto.png",
                "email"=>"sodikin@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>18,
                "role_id"=>2,
                "name"=>"Michel Gerald S",
                "image"=>"user/foto.png",
                "email"=>"gerald@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>19,
                "role_id"=>2,
                "name"=>"Wiwin Widiasari",
                "image"=>"user/foto.png",
                "email"=>"wiwin@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>20,
                "role_id"=>2,
                "name"=>"Arif Sunandar",
                "image"=>"user/foto.png",
                "email"=>"arif@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>21,
                "role_id"=>2,
                "name"=>"Yolie/Sutarsih",
                "image"=>"user/foto.png",
                "email"=>"yolie@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>22,
                "role_id"=>2,
                "name"=>"Rahmat Taufik",
                "image"=>"user/foto.png",
                "email"=>"rahmat@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>23,
                "role_id"=>2,
                "name"=>"Susanto",
                "image"=>"user/foto.png",
                "email"=>"susanto@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>24,
                "role_id"=>2,
                "name"=>"Andri Aurix",
                "image"=>"user/foto.png",
                "email"=>"andri@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>25,
                "role_id"=>2,
                "name"=>"Bagas",
                "image"=>"user/foto.png",
                "email"=>"bagas@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>26,
                "role_id"=>2,
                "name"=>"Dani Purnama",
                "image"=>"user/foto.png",
                "email"=>"dani@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>27,
                "role_id"=>2,
                "name"=>"Patrianoor",
                "image"=>"user/foto.png",
                "email"=>"patrianoor@member.com",
                "password"=>bcrypt("password")
            ],[
                "id"=>28,
                "role_id"=>2,
                "name"=>"H. Abdul Rahman/Umaysiah",
                "image"=>"user/foto.png",
                "email"=>"Rahman@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>29,
                "role_id"=>2,
                "name"=>"Willy Permana Putra/Heny",
                "image"=>"user/foto.png",
                "email"=>"willy@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>30,
                "role_id"=>2,
                "name"=>"Rosida",
                "image"=>"user/foto.png",
                "email"=>"rosida@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>31,
                "role_id"=>2,
                "name"=>"Yuda Permana/Susi",
                "image"=>"user/foto.png",
                "email"=>"yuda@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>32,
                "role_id"=>2,
                "name"=>"Suripto/Mutmaeli",
                "image"=>"user/foto.png",
                "email"=>"suripto@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>33,
                "role_id"=>2,
                "name"=>"Riva Mahandira",
                "image"=>"user/foto.png",
                "email"=>"riva@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>34,
                "role_id"=>2,
                "name"=>"Amrizal/Endah",
                "image"=>"user/foto.png",
                "email"=>"amrizal@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>35,
                "role_id"=>2,
                "name"=>"Yusa Listiawan/Evy",
                "image"=>"user/foto.png",
                "email"=>"yusa@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>36,
                "role_id"=>2,
                "name"=>"Purwanto/Ari",
                "image"=>"user/foto.png",
                "email"=>"purwanto@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>37,
                "role_id"=>2,
                "name"=>"Hanifah",
                "image"=>"user/foto.png",
                "email"=>"hanifah@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>38,
                "role_id"=>2,
                "name"=>"Heddy/Agustina",
                "image"=>"user/foto.png",
                "email"=>"heddy@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>39,
                "role_id"=>2,
                "name"=>"Sumiati",
                "image"=>"user/foto.png",
                "email"=>"sumiati@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>40,
                "role_id"=>2,
                "name"=>"Aditya/Villy",
                "image"=>"user/foto.png",
                "email"=>"aditya@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>41,
                "role_id"=>2,
                "name"=>"Tati Suhartaty",
                "image"=>"user/foto.png",
                "email"=>"tati@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>42,
                "role_id"=>2,
                "name"=>"Agni Ahmad",
                "image"=>"user/foto.png",
                "email"=>"agni@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>43,
                "role_id"=>2,
                "name"=>"Bravonco/Icha",
                "image"=>"user/foto.png",
                "email"=>"bravonco@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>44,
                "role_id"=>2,
                "name"=>"Sumarjo/Vera",
                "image"=>"user/foto.png",
                "email"=>"sumarjo@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>45,
                "role_id"=>2,
                "name"=>"Dedy Suwesdi/Anita",
                "image"=>"user/foto.png",
                "email"=>"dedy@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>46,
                "role_id"=>2,
                "name"=>"Hasby/jen Utami",
                "image"=>"user/foto.png",
                "email"=>"hasby@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>47,
                "role_id"=>2,
                "name"=>"Fahmi/Relly",
                "image"=>"user/foto.png",
                "email"=>"fahmi@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>48,
                "role_id"=>2,
                "name"=>"Pupung/Apriandi",
                "image"=>"user/foto.png",
                "email"=>"pupung@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>49,
                "role_id"=>2,
                "name"=>"Aris Makharizal/Rita",
                "image"=>"user/foto.png",
                "email"=>"aris@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>50,
                "role_id"=>2,
                "name"=>"Budi Setyawan/Nunung",
                "image"=>"user/foto.png",
                "email"=>"setyawan@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>51,
                "role_id"=>2,
                "name"=>"Riki Subekti/Dya",
                "image"=>"user/foto.png",
                "email"=>"subekti@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>52,
                "role_id"=>2,
                "name"=>"Nanda Andre/Arum",
                "image"=>"user/foto.png",
                "email"=>"nanda@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>53,
                "role_id"=>2,
                "name"=>"Abdurrahman/Enung",
                "image"=>"user/foto.png",
                "email"=>"abdurrahman@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>54,
                "role_id"=>2,
                "name"=>"Devi Permana/Atik",
                "image"=>"user/foto.png",
                "email"=>"devi@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>55,
                "role_id"=>2,
                "name"=>"Henkie Titus Bento",
                "image"=>"user/foto.png",
                "email"=>"henkie@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>56,
                "role_id"=>2,
                "name"=>"Apriadi/Nita",
                "image"=>"user/foto.png",
                "email"=>"apriadi@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>57,
                "role_id"=>2,
                "name"=>"Agung Triana/Een",
                "image"=>"user/foto.png",
                "email"=>"agung@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>58,
                "role_id"=>2,
                "name"=>"LBH",
                "image"=>"user/foto.png",
                "email"=>"lbh@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>59,
                "role_id"=>2,
                "name"=>"Fajrin/Irma",
                "image"=>"user/foto.png",
                "email"=>"fajrin@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>60,
                "role_id"=>2,
                "name"=>"Nurman Hakim/Restie",
                "image"=>"user/foto.png",
                "email"=>"nurman@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>61,
                "role_id"=>2,
                "name"=>"M. Hartopo/Fita",
                "image"=>"user/foto.png",
                "email"=>"hartopo@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>62,
                "role_id"=>2,
                "name"=>"Rahmansyah P. S",
                "image"=>"user/foto.png",
                "email"=>"rahmansyah@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>63,
                "role_id"=>2,
                "name"=>"Dedi Turmudi/Novi",
                "image"=>"user/foto.png",
                "email"=>"turmudi@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>64,
                "role_id"=>2,
                "name"=>"Yusuf/Arum",
                "image"=>"user/foto.png",
                "email"=>"yusuf@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>65,
                "role_id"=>2,
                "name"=>"Suharyanto/Farida",
                "image"=>"user/foto.png",
                "email"=>"suharyanto@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>66,
                "role_id"=>2,
                "name"=>"Nuraisyah",
                "image"=>"user/foto.png",
                "email"=>"nuraisyah@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>67,
                "role_id"=>2,
                "name"=>"Tidak Dikenal 2",
                "image"=>"user/foto.png",
                "email"=>"unknown2@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>68,
                "role_id"=>2,
                "name"=>"Amin Mubarok/Aam",
                "image"=>"user/foto.png",
                "email"=>"amin@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>69,
                "role_id"=>2,
                "name"=>"Ono Surono/Anggi",
                "image"=>"user/foto.png",
                "email"=>"ono@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>70,
                "role_id"=>2,
                "name"=>"M. Taufik/Yeti",
                "image"=>"user/foto.png",
                "email"=>"taufik@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>71,
                "role_id"=>2,
                "name"=>"Felix Rifaldi/Nani",
                "image"=>"user/foto.png",
                "email"=>"felix@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>72,
                "role_id"=>2,
                "name"=>"Suhardi/Nunik",
                "image"=>"user/foto.png",
                "email"=>"suhardi@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>73,
                "role_id"=>2,
                "name"=>"Roni Faslah/Desy",
                "image"=>"user/foto.png",
                "email"=>"roni@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>74,
                "role_id"=>2,
                "name"=>"Mastur/Hesti",
                "image"=>"user/foto.png",
                "email"=>"mastur@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>75,
                "role_id"=>2,
                "name"=>"Ryan Ramadhan/Nurul",
                "image"=>"user/foto.png",
                "email"=>"ryan@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>76,
                "role_id"=>2,
                "name"=>"Ega Marapies/Ella",
                "image"=>"user/foto.png",
                "email"=>"ega@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>77,
                "role_id"=>2,
                "name"=>"Abdul Rohman",
                "image"=>"user/foto.png",
                "email"=>"rohman@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>78,
                "role_id"=>2,
                "name"=>"Sigit Sutrisno/Puput",
                "image"=>"user/foto.png",
                "email"=>"sigit@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>79,
                "role_id"=>2,
                "name"=>"Ismanto/Entin",
                "image"=>"user/foto.png",
                "email"=>"ismanto@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>80,
                "role_id"=>2,
                "name"=>"Prio Wibowo/Eva",
                "image"=>"user/foto.png",
                "email"=>"prio@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>81,
                "role_id"=>2,
                "name"=>"Devi Heriyadi/Rosalina",
                "image"=>"user/foto.png",
                "email"=>"heriyadi@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>82,
                "role_id"=>2,
                "name"=>"Rico",
                "image"=>"user/foto.png",
                "email"=>"rico@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>83,
                "role_id"=>2,
                "name"=>"Taryono",
                "image"=>"user/foto.png",
                "email"=>"taryono@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>84,
                "role_id"=>2,
                "name"=>"Jupri/Heny",
                "image"=>"user/foto.png",
                "email"=>"jupri@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>85,
                "role_id"=>2,
                "name"=>"Sandi",
                "image"=>"user/foto.png",
                "email"=>"sandi@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>86,
                "role_id"=>2,
                "name"=>"Reso",
                "image"=>"user/foto.png",
                "email"=>"reso@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>87,
                "role_id"=>2,
                "name"=>"Hari Pangestu/Rosalia",
                "image"=>"user/foto.png",
                "email"=>"hari@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>88,
                "role_id"=>2,
                "name"=>"Deddy Hadyanto/Sisca",
                "image"=>"user/foto.png",
                "email"=>"deddy@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>89,
                "role_id"=>2,
                "name"=>"Dadan Hamdani/Sarah",
                "image"=>"user/foto.png",
                "email"=>"hamdani@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>90,
                "role_id"=>2,
                "name"=>"Andriana Setiady/Dini",
                "image"=>"user/foto.png",
                "email"=>"andriana@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>91,
                "role_id"=>2,
                "name"=>"Ade",
                "image"=>"user/foto.png",
                "email"=>"ade@member.com",
                "password"=>bcrypt("password")
            ],[
                "id"=>92,
                "role_id"=>2,
                "name"=>"Wawan Setiawan",
                "image"=>"user/foto.png",
                "email"=>"wawan@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>93,
                "role_id"=>2,
                "name"=>"Susanto/Sri",
                "image"=>"user/foto.png",
                "email"=>"susanto2@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>94,
                "role_id"=>2,
                "name"=>"Kuswayana",
                "image"=>"user/foto.png",
                "email"=>"kuswayana@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>95,
                "role_id"=>2,
                "name"=>"Sukani",
                "image"=>"user/foto.png",
                "email"=>"sukani@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>96,
                "role_id"=>2,
                "name"=>"Suwondo/Euis",
                "image"=>"user/foto.png",
                "email"=>"suwondo@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>97,
                "role_id"=>2,
                "name"=>"Karwanudin/Amalia",
                "image"=>"user/foto.png",
                "email"=>"karwanudin@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>98,
                "role_id"=>2,
                "name"=>"Ridza",
                "image"=>"user/foto.png",
                "email"=>"ridza@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>99,
                "role_id"=>2,
                "name"=>"Asgap Noviansyah/Husnul",
                "image"=>"user/foto.png",
                "email"=>"asgap@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>100,
                "role_id"=>2,
                "name"=>"Hasan/Joko Susilo",
                "image"=>"user/foto.png",
                "email"=>"hasan@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>101,
                "role_id"=>2,
                "name"=>"Agung/Ersy",
                "image"=>"user/foto.png",
                "email"=>"ersy@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>102,
                "role_id"=>2,
                "name"=>"Roni/Tari",
                "image"=>"user/foto.png",
                "email"=>"tari@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>103,
                "role_id"=>2,
                "name"=>"Asep S/Sandi",
                "image"=>"user/foto.png",
                "email"=>"asep@member.com",
                "password"=>bcrypt("password")
            ],
            [
                "id"=>104,
                "role_id"=>2,
                "name"=>"Yusron/Minawati",
                "image"=>"user/foto.png",
                "email"=>"yusron@member.com",
                "password"=>bcrypt("password")
            ],

        ];

        User::insert($data);
    }
}
